spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financeapp
    username: finance
    password: finance123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 4e635266556a586e3272357538782f413f4428472b4b6250645367566b597033
  expiration: 86400000   # 24h in ms

logging:
  level:
    com.financeapp: INFO
    org.springframework.security: WARN
